### ISSUE TITLE
game goes too fast

### ISSUE THREAD

**Issue by nedelio** [thomaswp/JunimoKartWeb#1]
the game goes too fast, i think it adapts to the fps, would appreciate if you find a fix

**Comment by arikomay** [comment]
This same issue is happening to me and friends. When the link to the browser is clicked, the game is like in hyper-speed. It doesn't happen on my work computer, but it goes insanely too fast on my home computer. Would love if there was a fix to this, I like practicing specific levels and playing without opening the game!

**Comment by thomaswp** [comment]
Glad you're enjoying it. I'm not able to reproduce the bug on my end. I tried a faster and slower computer and both behave normally. Game speed should be tied to time, not framerate. Can you say what browser/system you're using and copy any logs you see in the output, and check for errors in your [web console](https://support.monday.com/hc/en-us/articles/360002197259-How-to-open-the-developer-console)?

**Comment by Firalon** [comment]
Hi, we had the same problem with some friends and it does seem to be linked with framerate.
On my laptop, when I set my refresh rate to 60Hz, the game speed seems good, but when I set it to 144Hz, the game is ultra fast.

**Comment by thomaswp** [comment]
@Firalon thanks, that explains it! Seems like an issue in JSIL, and may not be straightforward to fix on my end.

However, it also looks like there's a workaround - just append `?forceSetTimeout` to the URL, e.g. https://thomaswp.github.io/JunimoKartWeb/Source/?forceSetTimeout

This uses a timeout rather than requestAnimationFrame, so it's tied to time passed instead of refresh rate.

It shouldn't be hard to add that as an option in the form - I'll try to get around to that.

**Comment by thomaswp** [comment]
I added a checkbox to enable this option - hope it helps!
